services:
  - type: web
    name: gps-fastapi-upload
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11